# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: "Sample Scenario"
description: "Suggest a new API Management Sample Scenario."
title: "[Scenario]: <title>"
labels: ["scenario"]
type: "Feature"
assignees:
  - simonkurtz-MSFT
body:
  - type: markdown
    attributes:
      value: |
        ## Scenario Request

        Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature
    attributes:
      label: "Describe the scenario"
      description: "What scenario are you proposing?"
      placeholder: "Please describe the sample scenario / use case you are proposing. What should it demonstrate?"
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: "Improvement to Project"
      description: "How will it improve this project?"
      placeholder: "Please describe how this feature will improve the project. What value does it provide that you currently do not have? How does it help YOU?"
    validations:
      required: true

  - type: dropdown
    id: collaborate
    attributes:
      label: "Are you able to collaborate and/or submit a pull request?"
      description: "Select one."
      options:
        - "Yes"
        - "No"
    validations:
      required: true
