# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: "Sample Scenario Request"
description: "Suggest a new API Management Sample Scenario."
title: "[Scenario]: <title>"
labels: ["triage"]
type: "Feature"
assignees:
  - simonkurtz-MSFT
body:
  - type: markdown
    attributes:
      value: |
        ## Scenario Request

        Please fill out the form below to help us understand your request. This is a more specialized feature request specifically for proposing sample scenarios that can be used to demonstrate the capabilities of API Management.
