# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: "Sample Scenario"
description: "Suggest a new API Management Sample Scenario."
title: "[Scenario]: <title>"
labels: ["triage"]
type: "Feature"
assignees:
  - simonkurtz-MSFT
body:
  - type: markdown
    attributes:
      value: |
        ## Scenario Request

        Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature
    attributes:
      label: "Describe the scenario"
      description: "What scenario are you proposing?"
      placeholder: "Please describe the sample scenario / use case you are proposing. What should it demonstrate?"
    validations:
      required: true
